name: Ruby

on:
  push:
  pull_request:
  schedule:
    - cron: '0 12 1 * *'

jobs:
  rspec:
    continue-on-error: ${{ endsWith(matrix.ruby, 'head') }}
    strategy:
      matrix:
        ruby: [3.0, 3.1, 3.2, 3.3, 3.4, head]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Run tests
      run: bundle exec rake spec
